#version 460 core
///Fast voxel clear

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
layout (rgba8, binding = 0) uniform image3D outVoxel;
layout (rgba8, binding = 1) uniform image3D outAlbedo;
layout (rgba8, binding = 2) uniform image3D outNormal;

void main(void)
{
	ivec3 pixel = ivec3(gl_GlobalInvocationID);
	imageStore(outVoxel, pixel, vec4(0));
	imageStore(outAlbedo, pixel, vec4(0));
	imageStore(outNormal, pixel, vec4(0));
}